### ISSUE TITLE
URL constants seem backwards?

### ISSUE THREAD

**Issue by pbreed** [jmccl/acme-lw#16]
This is from acme-lw.cpp
It seems backwards to me....
const char * productionDirectoryUrl = "https://acme-staging-v02.api.letsencrypt.org/directory";
const char * stagingDirectoryUrl = "https://acme-v02.api.letsencrypt.org/directory";

**Comment by jmccl** [comment]
Well, that's bad. I thought I had this code running in a production environment but I checked and never updated it for the last check-in. Should be fixed now. Thanks for the bug.
