### ISSUE TITLE
405 malformed against staging

### ISSUE THREAD

**Issue by degetz** [jmccl/acme-lw#5]
Hi,

When I try to run against the staging environment it responds with 405:

`Running against staging environment.

Failed with error: Response code of 405 contacting https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1249714784 with response of:
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Method not allowed",
  "status": 405
}`

Looks like it is due to:
https://github.com/letsencrypt/boulder/issues/4577

**Comment by jmccl** [comment]
Thanks for putting this in. Let me take a look.

**Comment by jmccl** [comment]
I've checked in a fix. Let me know if you've got any further issues.

Thanks for finding the source of the problem.

**Comment by degetz** [comment]
Thanks! Works nicely.
